### ISSUE TITLE
Upload images to wiki

### ISSUE THREAD

**Issue by LiXizhi** [LiXizhi/ParaCraft#1]
One can drag and drop images here
你可以拖动想上传的图片到这里

**Comment by LiXizhi** [comment]
![editbutton](https://cloud.githubusercontent.com/assets/94537/12637319/360cc742-c5cf-11e5-9a1f-551a34473f70.png)

**Comment by LiXizhi** [comment]
![e_key_open_inventory](https://cloud.githubusercontent.com/assets/94537/13378227/c6635d02-de38-11e5-8e5e-2781a0f642e8.png)

**Comment by yjstcb** [comment]
![image](https://cloud.githubusercontent.com/assets/13567673/13769319/a6997a28-eab9-11e5-82dd-85eebe6ec1d9.png)

**Comment by LiXizhi** [comment]
![questitem](https://cloud.githubusercontent.com/assets/94537/14173465/9852bf1a-f770-11e5-8f04-491efb72f73e.png)

**Comment by LiXizhi** [comment]
![questitem](https://cloud.githubusercontent.com/assets/94537/14173488/c6ea17ec-f770-11e5-9968-87846b9b46d3.png)

**Comment by LiXizhi** [comment]
![image](https://cloud.githubusercontent.com/assets/94537/17135090/88557b7e-5360-11e6-9bbf-8cc8eaa3fceb.png)

**Comment by LiXizhi** [comment]
![image](https://cloud.githubusercontent.com/assets/94537/18039502/44626a68-6dd6-11e6-881a-2c6ce483f116.png)

**Comment by LiXizhi** [comment]
![image](https://cloud.githubusercontent.com/assets/94537/18075582/9b3c06dc-6ea8-11e6-948f-3d378298066b.png)

**Comment by LiXizhi** [comment]
![image](https://cloud.githubusercontent.com/assets/94537/18092503/1711ca52-6eff-11e6-9003-e0cb174e8196.png)

**Comment by LiXizhi** [comment]
![image](https://cloud.githubusercontent.com/assets/94537/18742473/00e302c4-80e7-11e6-9135-0b6ae7425d3b.png)

**Comment by LiXizhi** [comment]
![image](https://cloud.githubusercontent.com/assets/94537/19898112/afe292d0-a095-11e6-872b-fcec7b5aab76.png)
