### ISSUE TITLE
联机图片同步时支持拉伸

### ISSUE THREAD

**Issue by yuki1206** [LiXizhi/ParaCraft#100]
目前联机时，图片能够支持同步的
但是大小的缩放没有支持
所以看到的情况就是这样，希望修复
![qq 20160920161630](https://cloud.githubusercontent.com/assets/19921244/18662635/cabae6fc-7f4d-11e6-9f25-603e0f8e7a1b.png)

**Comment by ExerciseBook** [comment]
#100祝贺！
