### ISSUE TITLE
客户端放相册后主机看不到 主机也无法编辑相册

### ISSUE THREAD

**Issue by Soul-Kim** [LiXizhi/ParaCraft#103]
![image](https://cloud.githubusercontent.com/assets/17987561/18869221/f1a4d472-84dd-11e6-9b12-a02535631528.png)

**Comment by LiXizhi** [comment]
暂时只支持HTTP贴图。 本地文件同步暂时还不支持。

**Comment by Soul-Kim** [comment]
是http贴图~

**Comment by LiXizhi** [comment]
我这里测试是正确的。 但是修复了无法显示https贴图的Bug。
