### ISSUE TITLE
骨骼缩放问题

### ISSUE THREAD

**Issue by PTjack** [LiXizhi/ParaCraft#104]
骨骼初始时期，使用缩放功能会出现不合理操作，吸附在骨骼的物体出现脱离骨骼中心轴偏移的现象。但当骨骼在初始时期使用过旋转功能时再使用缩放功能，却能合理操作，不会出现脱离骨骼的中心轴现象。

**Comment by LiXizhi** [comment]
应该没有这个问题， 需要更多的图
