### ISSUE TITLE
[bug]联机下传送石问题

### ISSUE THREAD

**Issue by Soul-Kim** [LiXizhi/ParaCraft#108]
![qq 20161011163354](https://cloud.githubusercontent.com/assets/17987561/19263804/b8cca4b0-8fd0-11e6-8c07-3e60b1b66253.png)
搭了 这么一个东西，下面红石上面传送石，联机下房主站上去之后可以下来，其他玩家站上去就被吸住下不来了

**Comment by LiXizhi** [comment]
目前就是这样设计的。 暂时没有很好的办法。
