### ISSUE TITLE
FBX模型支持引入镜面材质

### ISSUE THREAD

**Issue by yuki1206** [LiXizhi/ParaCraft#109]
![qq 20161013172312](https://cloud.githubusercontent.com/assets/19921244/19343745/063dbeba-916a-11e6-867a-643588648d88.png)
在FBX上指定某块区域，使他能够读取现有引擎的镜面功能

**Comment by LiXizhi** [comment]
https://github.com/LiXizhi/ParaCraftSDK/wiki/FBXModel

> it is now supported.

![image](https://cloud.githubusercontent.com/assets/94537/19434681/81c3d466-9499-11e6-8cfb-380cbb377f65.png)
