### ISSUE TITLE
[suggestion]在同一物品栏能容纳不同颜色的彩色方块

### ISSUE THREAD

**Issue by LovelyCatHyt** [LiXizhi/ParaCraft#111]
这样就不需要频繁地取色了。
目前物品栏只要是同种彩色方块，都只能有一种颜色；而在建模的时候常常要用到固定几种颜色的彩色方块，现在来讲还是挺麻烦的呢。

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
