### ISSUE TITLE
[bug] 联机下客户端使用/runat有问题

### ISSUE THREAD

**Issue by Soul-Kim** [LiXizhi/ParaCraft#113]
/runat 需要@玩家名，但在客户端里其他玩家都是没有名字的 无法指定对象

**Comment by Soul-Kim** [comment]
比如要对指定玩家（图中红圈）大小进行改变，/runat @all /scaling @__MP__1965612 5
结果就是下图，并没有成功
![1](https://cloud.githubusercontent.com/assets/17987561/19544004/1eea94d0-96ae-11e6-89c2-1f0ba2b8c13a.png)
![2](https://cloud.githubusercontent.com/assets/17987561/19544005/1ef0cda0-96ae-11e6-9817-048436e24a44.png)

**Comment by ExerciseBook** [comment]
【这个嵌套用法我给满分

**Comment by LiXizhi** [comment]
- fixed username on client side.
- fixed @playername for a dozen of player related commands like /scaling /facing, /velocity, /gravity, /take, /give, /clearbag, /say, /set, /walk, /lookat, /disableinput ...


e.g.
`/runtat @all /give 62`
