### ISSUE TITLE
[重新描述的建议]在编辑模式下能够不借助电影方块编辑bmax模型

### ISSUE THREAD

**Issue by LovelyCatHyt** [LiXizhi/ParaCraft#119]
![image](https://cloud.githubusercontent.com/assets/20336911/19828032/07161662-9dee-11e6-8995-17870b10d8ba.png)
我的意思是。在非电影模式下，能够调出这个界面，然后更改放在场景中骨骼的角度什么的。。。
这样呢，就能在游戏模式下直接看到被编辑过的模型，而不是保存bmax时的形状。
【这样理解了吧_(:з」∠)_

**Comment by LiXizhi** [comment]
OK  bmax目前只能是静态无动画的， 但是我们计划加入骨骼动画。
具体细节为：
- 将包含bmax的电影方块保存为bmax模型，bmax模型默认为电影方块中的形象和动作（或动画）。 

Accepted. This feature may be added some time soon.  If you need it badly, describe your use case here.

**Comment by LovelyCatHyt** [comment]
突然发现，其实现在就可以实现这个效果。
在电影方块的任务栏删掉摄像机就好。
【顺便在最后一帧加个/activate还能实现循环播放
