### ISSUE TITLE
玻璃遮挡玩家名

### ISSUE THREAD

**Issue by yjstcb** [LiXizhi/ParaCraft#12]
玻璃会遮挡玩家头顶名称，如下图
![image](https://cloud.githubusercontent.com/assets/13567673/15203313/e309499a-1834-11e6-9210-3b35c84dfa67.png)
![image](https://cloud.githubusercontent.com/assets/13567673/15203318/eb990924-1834-11e6-8b66-a9b753adc6c2.png)

**Comment by LiXizhi** [comment]
fix headon display GUI order with alpha-blended blocks
