### ISSUE TITLE
FBX支持原.x的离子动画效果

### ISSUE THREAD

**Issue by yuki1206** [LiXizhi/ParaCraft#132]
目前FBX无法像.x一样一边移动一边播放动画，希望能够改进这个功能，使.x能向FBX完成过渡

**Comment by LiXizhi** [comment]
一样一边移动一边播放动画是可以的 （例如主角）。 应该是支持粒子发射器。

**Comment by yjstcb** [comment]
NPC在空中飞行时，不停刷新目的地坐标，NPC的动画就会鬼畜
