### ISSUE TITLE
[bug]在半砖方块上起跳，有时会有延迟

### ISSUE THREAD

**Issue by Soul-Kim** [LiXizhi/ParaCraft#137]
按空格之后大约半秒之后才跳起来

**Comment by yjstcb** [comment]
![image](https://cloud.githubusercontent.com/assets/13567673/21418581/3647ee08-c85d-11e6-9e51-b0254e15a293.png)
如上图

**Comment by LiXizhi** [comment]
@
无法复现，请提供更详细的复现步骤，谢谢~

**Comment by Soul-Kim** [comment]
把后缀改成zip即存档
[jump.txt](https://github.com/LiXizhi/ParaCraft/files/672734/jump.txt)

**Comment by yjstcb** [comment]
请使用@Soul—kim 上传的地图
复现步骤：
1.输入/addrule Player CanJumpInAir false
2.切到播放模式
3.到悬空的半砖上去跳
此时会发现跳不灵

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks

need to update C++ dll
