### ISSUE TITLE
【BUG】人物站立在物理模型上后，因帧数刷新而产生全屏抖动

### ISSUE THREAD

**Issue by yuki1206** [LiXizhi/ParaCraft#144]
抖动部分不只物理模型，方块也会随之而抖
![qq 20170116102046](https://cloud.githubusercontent.com/assets/19921244/21968996/8964b2ac-dbd5-11e6-827a-725479e1b54b.png)

**Comment by LiXizhi** [comment]
我可以复现了，谢谢，会尽快修复

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
