### ISSUE TITLE
[需求]场景物体选中问题

### ISSUE THREAD

**Issue by e-setup** [LiXizhi/ParaCraft#148]
paracraft场景中会导入很多物体，其中有很多重叠在一起的(模型重叠，甚至坐标都重叠)。当需要根据鼠标悬停那个点上能看到的像素来选中对应的那个物体，此时需要一个很精确的对象选择接口(ray-picking)，请问这个怎么实现？

**Comment by LiXizhi** [comment]
supported see BufferPicking api
