### ISSUE TITLE
场景中的物体渲染顺序问题

### ISSUE THREAD

**Issue by e-setup** [LiXizhi/ParaCraft#149]
现在paracraft中导入的模型，如果一个大的物体全包裹住一个小的物体，并且大的物体处在半透明状态下，怎么能让小的物体渲染的时候处在最外层？

**Comment by LiXizhi** [comment]
there is a "RenderImportance" property on ParaObject, did you try that?

**Comment by e-setup** [comment]
tried. if the object I want to highlight is inside of another, then no matter how I change the "RenderImportance", it's still covered by the outer object, visually.

**Comment by LiXizhi** [comment]
ic, i guess transparent objects are always rendered last regardless of render order property.  I will think about it

**Comment by ExerciseBook** [comment]
为啥突然间大家都说英文了

**Comment by LiXizhi** [comment]
use overlay object
