### ISSUE TITLE
Linux服务器和自动保存

### ISSUE THREAD

**Issue by PTjack** [LiXizhi/ParaCraft#154]
1、租了一个服务器有静态ip，如果我们想用服务器来搭私服，可以吗？

2、如果可以搭服务器，那我们可不可服务器里开多个客户端，让多个高校的学生都在线搭建？

3、多人在线搭一个学校；多人在线分为几组搭不同的学校（几个学校在不同世界里）？

**Comment by ExerciseBook** [comment]
据我看来那是可以的 → ps.61.com
