### ISSUE TITLE
[bug]复制命令方块，命令内容出错

### ISSUE THREAD

**Issue by LovelyCatHyt** [LiXizhi/ParaCraft#156]
在命令方块中的物品栏里放命令行（长得像书一样的东西）
写上一堆命令

然后
1、复制到远处运行，出错
2、保存为模板，出错
3、检查发现无论是复制还是保存为模板，都会：
开头多了一段【{name="![CDATA[","】，
结尾多了一段【",}】
(中文大括号方便文本内容区分)
就是这样。

**Comment by LovelyCatHyt** [comment]
<pe:blocktemplate author_nid="0" player_pos="19260,13,19244" relative_motion="false" pivot="19260,16,19247" name="testCMD" creation_date="2017-03-30_180847">
	<pe:blocks>{{0,0,0,212,[6]={{name="inventory",{{name="![CDATA[","{name=\"![CDATA[\",\"/activate ~ ~-2 ~#/if $(testblock ~0 ~1 ~-2 156) == true then#--第一层血条#    /if $(testblock ~0 ~1 ~-1 156) == true then#        /translate ~0 ~1 ~-1(0 0 3) to 0 0 -1#    /else#        /setblock ~0 ~1 ~-2(0 0 4) 97#    /fi#/elseif $(testblock ~0 ~1 ~-2 97) == true then#--第二层血条#    /if $(testblock ~0 ~1 ~-1 97) == true then#        /translate ~0 ~1 ~-1(0 0 3) to 0 0 -1#    /else#        /setblock ~0 ~1 ~-2(0 0 4) 148#    /fi#/elseif $(testblock ~0 ~1 ~-2 148) == true then#--第二层血条#    /if $(testblock ~0 ~1 ~-1 148) == true then#        /translate ~0 ~1 ~-1(0 0 3) to 0 0 -1#    /else#        /activate ~0 ~-3 ~-1#    /fi#/fi\",}",},name="slot",attr={count=1,id=10059,},},},name="entity",attr={bz=19247,bx=19260,class="EntityCommandBlock",item_id=212,by=16,},},},}
	</pe:blocks>
</pe:blocktemplate>
这个是里面的文本，不知道为什么不能上传ZIP

**Comment by ExerciseBook** [comment]
```
<pe:blocktemplate author_nid="0" player_pos="19260,13,19244" relative_motion="false" pivot="19260,16,19247" name="testCMD" creation_date="2017-03-30_180847">
	<pe:blocks>
		{
			{0,0,0,212,
				[6]={
						{
							name="inventory",
							{
								{
									name="![CDATA[",
									"{name="![CDATA[","/activate~~-2~#/if$(testblock~0~1~-2156)==truethen#--第一层血条#/if$(testblock~0~1~-1156)==truethen#/translate~0~1~-1(003)to00-1#/else#/setblock~0~1~-2(004)97#/fi#/elseif$(testblock~0~1~-297)==truethen#--第二层血条#/if$(testblock~0~1~-197)==truethen#/translate~0~1~-1(003)to00-1#/else#/setblock~0~1~-2(004)148#/fi#/elseif$(testblock~0~1~-2148)==truethen#--第二层血条#/if$(testblock~0~1~-1148)==truethen#/translate~0~1~-1(003)to00-1#/else#/activate~0~-3~-1#/fi#/fi",}",
									
								},
								name="slot",
								attr={
									count=1,
									id=10059,
									
								},
								
							},
							
						},
						name="entity",
						attr={
							bz=19247,
							bx=19260,
							class="EntityCommandBlock",
							item_id=212,
							by=16,
							
						},
						
					},
			}
		,
		}

	</pe:blocks>
</pe:blocktemplate>
```

**Comment by LiXizhi** [comment]
我这里是好的。 没有出现问题
无法复现，请提供更详细的复现步骤，谢谢~
```
<pe:blocktemplate author_nid="0" creation_date="2017-11-15_003728" name="test" pivot="19243,5,19184" player_pos="19245,4,19180" relative_motion="false">
	<pe:blocks>{{0,0,0,212,[6]={attr={bx=19243,by=5,bz=19184,class="EntityCommandBlock",item_id=212,},name="entity",{name="cmd","/move @p home",},{name="inventory",{attr={count=1,id=10059,},name="slot",{name="![CDATA[","-- hello    world#/tip  你好",},},{attr={count=1,id=10054,},name="slot","test.lua",},},},},}
	</pe:blocks>
</pe:blocktemplate>
```
