### ISSUE TITLE
[bug]点【复制】按钮复制到奇怪的东西

### ISSUE THREAD

**Issue by LovelyCatHyt** [LiXizhi/ParaCraft#157]
在命令行书界面有【清空】【复制】【保存】等按钮
然而如果在命令内容中写了中文，
那么点【复制】之后，
剪切板里的中文部分变成一堆乱码
貌似是很久以前的问题了

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
