### ISSUE TITLE
急需升级视频输出像素，急需！！！！！！

### ISSUE THREAD

**Issue by PTjack** [LiXizhi/ParaCraft#158]
xizhi ,有个需求请优先完成以下，关于软件里输出成片的清晰度。帕拉卡和配天，那边都已经提出需求，配天那边是急需。需要升级软件输出短片的分辨率提高清晰度。因为现在电脑显示已经都在1680+以上的分辨率，视频输出的分辨率还在1280阶段。

**Comment by ttqf975414890** [comment]
建议开放 x264 编码器（如果是用这个）的更多自定义参数，如果可以，加上 Quick Sync 编码器。
离屏渲染也是个需要的地方。

**Comment by ExerciseBook** [comment]
ffmpeg大法好
