### ISSUE TITLE
【联机】优化联机带宽

### ISSUE THREAD

**Issue by yjstcb** [LiXizhi/ParaCraft#16]
20个人在线集中在几个房间内普通建造的时候，服务器带宽峰值在3M左右，估算1000人在线时，最高带宽需150M左右；
能否优化同步带来的带宽？

**Comment by LiXizhi** [comment]
目前按照第一人称的即时类需求做的。 带宽会随相互能看到的人成平方增长。 
例如6*6=36， 8*8=64。  
- 比较建议免费的房间应该设置人数上限。 例如4-6人。 
- 如果带宽是问题，CPU不是问题， 可以配置NPL，压缩数据包（地形数据已经压缩过了）。一般来说CPU是瓶颈，带宽不是问题。 视频网站一个用户就50M。
- 也可以降低同步频率，例如目前一秒3次， 改为3秒1次，带宽就少了9倍。

**Comment by ExerciseBook** [comment]
所以。。。这个反馈貌似暴露了很多信息 。什么房间人数之类的。。。。。
其实应该可以学学spigot之类的服务端的那类的优化。 可以达到8G内存 200人同一个世界没啥问题。
带宽要求也不高。
【我只是评论，可以无视掉
