### ISSUE TITLE
[BUG]人物跳转在两台电脑开启的客户端和服务器上，客户端的跳转距离过远会回到出生点

### ISSUE THREAD

**Issue by blchock** [LiXizhi/ParaCraft#163]
问题描述：在A电脑启动服务端/startserver 在B电脑启动客户端 /connect *.*.*.* ，B电脑执行/goto 17000 5 16000 或 move指令，或用代码执行SetToBlockPos/TeleportToBlockPos指令都无法将客户端正确传送到目标点，经常会到出生点
分析及尝试：
 一开始我们调用TeleportToBlockPos发现里面的实现就是SetToBlockPos，后面我们将packet_move从客户端发送到了服务端的NetServerHandler:handleMove，在里面屏蔽了距离过远的各种判断，但是发现这个函数只是将服务端玩家跳转到指定位置，过一会还是回来了,现象就像是客户端要求服务端跳到那里，但是服务端执行后发现自己并没有跳的必要就又回来了。代码如下：
local Packets = commonlib.gettable("MyCompany.Aries.Game.Network.Packets");
NPL.load("(gl)script/apps/Aries/Creator/Game/Network/NetworkMain.lua");
local NetworkMain = commonlib.gettable("MyCompany.Aries.Game.Network.NetworkMain");
local px,py,pz = BlockEngine:real(po.x,po.y,po.z)
EntityManager.GetPlayer():AddToSendQueue(Packets.PacketPlayerPosition:new():Init(px, py, py ,pz, EntityManager.GetPlayer().onGround));
后面我们发现EntityPlayerMP中的TeleportToBlockPos实现的更详细，像是要客户端跳转，我们就尝试了用另一种方式调用这个函数：
...
local NetworkMain = commonlib.gettable("MyCompany.Aries.Game.Network.NetworkMain");
local handleData = Packets.PacketPlayerPosition:new():Init(px, py, py ,pz, EntityManager.GetPlayer().onGround)
local str = NetworkMain:GetClient().net_handler:handleMove(handleData)
这样客户端好像都没有跳转过。NetClientHandler:handleMove好像是服务端指定用户端传送的代码，我们调用时并没有被执行，游戏一开始的时候执行过。PlayerManager:UpdateMovingPlayer中的代码每帧都会执行，里面实现的应该是指定每个客户端应该出现的位置。我们还是不理解移动相关的客户端和服务端的这些代码，不知道如何在服务端将用户传过去并同步客户端和服务器。注释掉NetServerHandler:handleMove的代码好像还是没用。我试着用move指令调用传入客户端id之后调用的还是Entity.lua中的Entity:TeleportToBlockPos，不会调用到EntityPlayerMP中的TeleportToBlockPos中，感觉Entity:TeleportToBlockPos的实现会有问题，其他的检测逻辑我们都没找到。

**Comment by ExerciseBook** [comment]
试一下 /move 命令那边的方法？

**Comment by blchock** [comment]
前提是在两台电脑上分别开客户端和服务端，有尝试过/move在服务端@其他人有时候还是会跳回来，在客户端@服务器服务端看画面一动也不动，客户端上服务器跳动了但是两边不同步。我需要实现的是无论在服务端还是客户端  自己的传送都能准确同步到两边同样显示

**Comment by kkvskkkk** [comment]
执行goto命令的时候， 服务器已经把角色移动到了指定坐标， 但是客户端发送PacketMove的时候， 包含了旧的坐标， 服务器端处理PacketMove消息的时候， 发现当前角色坐标（goto指定的坐标）和PacketMove附带的坐标距离太远， 于是启用-- server rule2: teleport to the given position.   使用-- server rule1: revert to old position 时结果正常。
