### ISSUE TITLE
[Suggestion]更加强大的function-call

### ISSUE THREAD

**Issue by LovelyCatHyt** [LiXizhi/ParaCraft#164]
经过简单的测试可以发现function和许多语言的“函数”功能差不多
但是作用域只在一个命令行区内
这里我说的命令行区，指的是一个命令方块输入框，或者是一本命令行书。
call的话，依托于function，也是类似的只能作用于一个命令行区╮(╯…╰)╭

所以我建议：
在一次执行function后，
在整个世界范围内建立一个函数
当该世界内执行call的时候，无论在其命令行区有没有这个函数的定义，也能执行它的功能。
甚至于，可以在创造模式下提供查看函数集的功能，方便查看和修改
( ╯▽╰)
【就像/goto一样】
这样能够对有大量命令方块世界的命令编辑带来便捷
(｡･∀･)ﾉﾞ

**Comment by LovelyCatHyt** [comment]
稍等。为什么我的字体发生了迷の变化？是不是触发了什么命令？？？

**Comment by LiXizhi** [comment]
高级的编程可以用MOD

**Comment by LiXizhi** [comment]
用代码方块
