### ISSUE TITLE
【BUG】ParaIO的open打开Jpeg格式会奔溃

### ISSUE THREAD

**Issue by blchock** [LiXizhi/ParaCraft#166]
我们现在使用的百度地图只有JPG格式的瓦片下载后才不会是3D的建模。我们需要加载jpg格式的图片
我已经将瓦片JPG图片发给您（其实任意jpg图片都可以用于测试），以下是测试代码：
-- test jpeg ParaIO.open
local raster1 = ParaIO.open("tile_normal1.jpg", "image"); echo("loadedImage tile_normal1");
local raster2 = ParaIO.open("tile_normal2.jpg", "image"); echo("loadedImage tile_normal2");
local raster3 = ParaIO.open("tile1.jpg", "image"); echo("loadedImage tile1");
local raster4 = ParaIO.open("tile2.jpg", "image"); echo("loadedImage tile2");
raster1:close();raster2:close();raster3:close();raster4:close();
-- test png ParaIO.open
local raster1 = ParaIO.open("tile1.png", "image"); echo("loadedImage tile1");
local raster2 = ParaIO.open("tile2.png", "image"); echo("loadedImage tile2");
local raster3 = ParaIO.open("tile3.png", "image"); echo("loadedImage tile3");
local raster4 = ParaIO.open("tile4.png", "image"); echo("loadedImage tile4");
raster1:close();raster2:close();raster3:close();raster4:close();
--
将这段代码放入定时器中不断执行，png的不会奔溃，jpg的会奔溃。

**Comment by kkvskkkk** [comment]
我来看看吧
