### ISSUE TITLE
【bug】在推荐作品那按分享作品 登陆后 必定触发这样的状况  卡在页面 且 关不掉客户端，打开软件后 先随意进一个推荐作品里 直接按分享

### ISSUE THREAD

**Issue by duting1993** [LiXizhi/ParaCraft#167]
![image](https://cloud.githubusercontent.com/assets/28430070/26399724/a1e1eb98-40b0-11e7-979d-3632fb90aaff.png)
在推荐作品那按分享作品 登陆后 必定触发这样的状况  卡在页面 且 关不掉客户端，打开软件后 先随意进一个推荐作品里 直接按分享

**Comment by kkvskkkk** [comment]
@lixizhi 这个版本和我们的不一样啊

**Comment by ExerciseBook** [comment]
楼上去更新一下吧。。。

**Comment by kkvskkkk** [comment]
截图功能概率性导致主线程死锁， 地图越复杂越容易出现  已修复。

**Comment by LiXizhi** [comment]
不是ScreenShot 问题造成的。 是WorldShare插件的BUG。 @big

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
