### ISSUE TITLE
TableDatabase 中文路径数据库连续打开写入，数据会存储到第一个打开的数据库中。

### ISSUE THREAD

**Issue by blchock** [LiXizhi/ParaCraft#168]
NPL.load("(gl)script/ide/System/Database/TableDatabase.lua");
local TableDatabase = commonlib.gettable("System.Database.TableDatabase");
--[[代码A]]
local db1 = TableDatabase:new():connect(commonlib.Encoding.Utf8ToDefault("中文路径1/"), function()
end);
db1.sys:insertOne({key="schoolName"},{name="华中科技大学"})
db1.sys:waitflush({})
--]]
--[[代码B]]
local db2 = TableDatabase:new():connect(commonlib.Encoding.Utf8ToDefault("苹果Apple商店/"), function()
end);
db2.sys:insertOne({key="schoolName"},{name="深圳大学"})
db2.sys:waitflush({})
--]]

问题描述：打开paracraft，按F12，在代码编辑器中粘贴上面代码，代码A和B分段执行（顺序随意），两个学校名字都会被存放到先创建的中文路径中的数据库中。
问题分析：只会出现在中文路径的数据库中，相同的数据库文件名和结构(本例中的.sys)，不同的中文路径，先后打开两个数据库数据会被存储到先打开的数据库中。

**Comment by kkvskkkk** [comment]
数据库连接后， 有2个操作
1. 创建目录
2. 创建数据库

我们的lua代码都是utf8格式， 创建目录所使用的api需要ansi， 本来想在ParaIO统一处理， 但是涉及到Open文件的地方比较负责， 所以只是在lua层做了简单处理

创建数据库的时候， c++代码有个bug， 前面把传入参数默认当作utf8处理， 后面又把传入参数当作ansi处理了，  已经改成统一按utf8处理

**Comment by ExerciseBook** [comment]
话说，路径为啥要用中文？感觉这样子很容易出事。
现在玩ParaCraft都用英文路径来搞了。

**Comment by blchock** [comment]
你会这么做但是客户不会这么做呀。 许多客户建存档是用中文的，比如学校名称

**Comment by ExerciseBook** [comment]
我记得最开始创意空间文件名命名规则是 日期_时间 23333 后来才变成了世界名字。
原来是给别人做的啊，我还以为是自己用，自己用的为防止出毛病我都英文化了【甚至是拼音。

**Comment by LiXizhi** [comment]
@kkvskkkk
