### ISSUE TITLE
【entity】编辑框中的预览图显示不全，建议预览图不随实物大小变化

### ISSUE THREAD

**Issue by yjstcb** [LiXizhi/ParaCraft#17]
entity类道具放置后，进行编辑放大，编辑框中的预览图显示不全，建议预览图不随实物大小变化。如下图：
![image](https://cloud.githubusercontent.com/assets/13567673/15813233/e5c7f22a-2bef-11e6-8fab-46d93b97c46b.png)

**Comment by ExerciseBook** [comment]
暴露身份 _(:з」∠)_

**Comment by LiXizhi** [comment]
Fixed in next release
- Fixed entity portrait scaling
