### ISSUE TITLE
[疑似bug] 客户端中的服务器无法开放到外网

### ISSUE THREAD

**Issue by ExerciseBook** [LiXizhi/ParaCraft#173]
![image](https://user-images.githubusercontent.com/6327311/28049311-1354b998-6629-11e7-97f0-d1b2b427e538.png)

![image](https://user-images.githubusercontent.com/6327311/28049312-1688cf96-6629-11e7-9ff3-6259faf3f3c4.png)

端口转发，DMZ主机都试过了，全部失败。最后我用本地开服务器，使用局域网连接，依然失败。

望早日修复。

还有人要等着用这个方法来做比赛作品的。

**Comment by LiXizhi** [comment]
我这里可以。 你是如何启动Server的？

**Comment by ExerciseBook** [comment]
今天又可以了。。怀疑和昨天我的mod冲突有关系。。
游戏目录多了一个 NPL_package 文件夹

**Comment by ExerciseBook** [comment]
现在遇到的问题是这样的。
![image](https://user-images.githubusercontent.com/6327311/28099549-bf2af5e0-66ef-11e7-8bf1-f41d6922ded6.png)
![image](https://user-images.githubusercontent.com/6327311/28099558-cc4b9e5a-66ef-11e7-8008-79188596d2df.png)
![image](https://user-images.githubusercontent.com/6327311/28099570-e0d326b8-66ef-11e7-8113-ae11c4c1500b.png)
![image](https://user-images.githubusercontent.com/6327311/28099580-f1c5bed6-66ef-11e7-8138-f68333e13d62.png)
