### ISSUE TITLE
[bug]带背景音乐的电影方块

### ISSUE THREAD

**Issue by LovelyCatHyt** [LiXizhi/ParaCraft#181]
当使用“背景音乐”轴播放音乐时，一般正常
但是如果把演员列表里的摄像机删去，就无法用红石、activate等方法播放了

**Comment by LovelyCatHyt** [comment]
事实上添加了【子电影方块】按照上述操作也会出现同样问题

**Comment by LiXizhi** [comment]
无法复现，请提供更详细的复现步骤，谢谢~
