### ISSUE TITLE
【道具】使用shift右键串联栏杆后，中间的横杆没有自动出现，再放置一个栏杆后才出现

### ISSUE THREAD

**Issue by yjstcb** [LiXizhi/ParaCraft#19]
使用shift右键串联栏杆后，中间的横杆没有自动出现，再放置一个栏杆后才出现
![image](https://cloud.githubusercontent.com/assets/13567673/15813275/3e335792-2bf0-11e6-93a9-330754089b8d.png)

**Comment by ExerciseBook** [comment]
还是老bug。提交过很多次了。不过这种更新bugMC里也有。所以也见怪不怪了 _(:з」∠)_
原来这里有更多的人提交bug啊。我一直都在 ParacraftSDK 项目那边提交。。难怪没有人回复一起讨论。。。

**Comment by LiXizhi** [comment]
fixed in next release
- fixed fill line task does not inform neighbor changes
