### ISSUE TITLE
【BMAX需求】

### ISSUE THREAD

**Issue by PTjack** [LiXizhi/ParaCraft#193]
【BMAX需求】：
BMAX模型支持BMAX模型的叠加生成。为了让模型可以更好的做到细节。
建造的BMAX模型在新建的方块模型中一同保存生成出新的BMAX形态。

**Comment by LiXizhi** [comment]
LiXizhi(lixizhi@yeah.net)  5:32:23 PM
之前是允许BMAX内部引用其他BMAX， 但是我们加入LOD之后， 这个功能不行了。 


LiXizhi(lixizhi@yeah.net)  5:33:55 PM
@兰志鸿 你看下如果引用的BMAX可以正常参与LOD是最好的， 最差情况是如果发现了引用，直接禁用LOD，使用旧代码。

**Comment by LovelyCatHyt** [comment]
吐槽：太好了终于有人提出这个了
我都差点忘了
--------------------------------
正文：
没有正文

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
