### ISSUE TITLE
【BUG】电影方块R快捷录制模式。

### ISSUE THREAD

**Issue by PTjack** [LiXizhi/ParaCraft#196]
【BUG】电影方块R快捷录制模式：
在电影方块建造演员后，自动进入播放模式，让一些用户错认为无法做建造录制的效果。当切换回编辑模式下，R快捷键丢失，需要鼠标手动去点击按钮。

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
