### ISSUE TITLE
【Bug】F4切换网格模式后，物品栏没有刷新

### ISSUE THREAD

**Issue by LovelyCatHyt** [LiXizhi/ParaCraft#197]
正常情况下，F4切换之后，物品栏没有发生变化。
直到按E键拖动滑动条刷新之后，物品栏里的方块才变成网格模式
从网格模式切换回去也是同样的情况

**Comment by LiXizhi** [comment]
里面的内容的预先渲染到图片中的。 不是每帧渲染。
