### ISSUE TITLE
【Bug】renderdist过小带来的问题

### ISSUE THREAD

**Issue by LovelyCatHyt** [LiXizhi/ParaCraft#198]
当视距设置非常小（10）时，渲染会鬼畜。。。
可以很明显看出以区块划分。。站在一个区块的边缘可以看到一片空白
另外建议以人物为中心计算渲染距离
这样在cameradist较大的时候也可以看清人物
![image](https://user-images.githubusercontent.com/20336911/28926799-756131d2-789b-11e7-8c04-cab8bd06b841.png)

**Comment by LiXizhi** [comment]
输入
```
/renderdist 10
```
需要能正确渲染。 

@kkvskkkk   please try to fix it and send pr.

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
