### ISSUE TITLE
【Suggestion】新建命令设置LOD

### ISSUE THREAD

**Issue by LovelyCatHyt** [LiXizhi/ParaCraft#199]
如题，在某些使用bmax的电影里开启LOD会十分尴尬。。
比如《黑与白》就是个很好的例子
最好还能设置LOD具体的降精度距离

**Comment by LovelyCatHyt** [comment]
那个 非常抱歉 现在才发现真的有lod这个命令
可以开关lod
嗯这个issue也差不多可以关闭了

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
