### ISSUE TITLE
联机地形显示不出

### ISSUE THREAD

**Issue by yjstcb** [LiXizhi/ParaCraft#2]
版本：0.7.243
新建地图开启联机之后 随意向一个方向走，会出现如图状况
方块显示不出来，但是方块是存在的，如下图
![image](https://cloud.githubusercontent.com/assets/13567673/14338306/9054f8a4-fca8-11e5-9790-91ed1583b82c.png)
![image](https://cloud.githubusercontent.com/assets/13567673/14338313/9ebab366-fca8-11e5-8a14-f873ff2b6a7a.png)
![image](https://cloud.githubusercontent.com/assets/13567673/14338319/b014707a-fca8-11e5-8415-e57ef5751ff3.png)

**Comment by LiXizhi** [comment]
fixed in next release
