### ISSUE TITLE
【联机】选中大量方块上下左右移动时，在移动路径上会有残留方块

### ISSUE THREAD

**Issue by yjstcb** [LiXizhi/ParaCraft#20]
依旧是上次那个问题，加入别人主机之后选中大量方块然后快速移动，在移动路径上会有残留方块。

**Comment by ExerciseBook** [comment]
我想说。。。这是老bug。。。

**Comment by LiXizhi** [comment]
Fixed in next release
- fix: local chunk changes are commited to server before applying server patch
