### ISSUE TITLE
paracra3d校园搭建功能的10分钟自动保存需求

### ISSUE THREAD

**Issue by adkevinchang** [LiXizhi/ParaCraft#203]
3d校园项目由于是远程多人搭建。如果出现断电或死机，就会造成搭建的作品没有保存。

增加自动保存空间的功能。每10分钟自动保存空间一次。

很紧急，谢谢！

**Comment by LiXizhi** [comment]
好的， 我写一个命令

/autosave 命令

也可以用命令方块自己实现。 

```
/t 10 /save
/activate ~1 self
```

**Comment by ExerciseBook** [comment]
/save
/t 
打到一半就被截胡了。。。

**Comment by adkevinchang** [comment]
/t 10 /save
/activate ~1 self

这个试了好像不行

**Comment by LiXizhi** [comment]
```
/autosave 
```
加入了， 可以加到出生点。 

Fixed in next release (已经修复，等下个版本发布. )  Thanks

**Comment by adkevinchang** [comment]
ok!
