### ISSUE TITLE
【bug】所有bmax在任何使用途径中显示都有问题

### ISSUE THREAD

**Issue by RyanGIggs** [LiXizhi/ParaCraft#206]
如图
![qq 20170823180501](https://user-images.githubusercontent.com/16772836/29611107-e504d79e-882e-11e7-81fc-50c95d7a2990.jpg)

**Comment by LiXizhi** [comment]
I am fixing it.

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
