### ISSUE TITLE
【显示】打碎方块一瞬间下方方块贴图未加载

### ISSUE THREAD

**Issue by yjstcb** [LiXizhi/ParaCraft#21]
![image](https://cloud.githubusercontent.com/assets/13567673/16000003/08bb781a-317c-11e6-887a-d47f22f3e105.png)
打碎方块的一瞬间，该方块下方的方块貌似加载会很慢，在加载出来之前，会呈现上图的样子。有没有办法解决加载慢问题呢，或者这个是什么原因导致的呢，能优化吗？

**Comment by LiXizhi** [comment]
> 原因是：光照和渲染缓存制作是在另外的线程异步完成的。 可能刚刚进入世界，队列中还有很多远处的数据没有做完，所以会慢。 当进入世界一段时间后，应该会快。 一般发生在4个Chunk的交接处。

**Comment by LiXizhi** [comment]
Fixed in next release
- Fixed possible missing gaps when rendering chunk boarder blocks,  the main thread will wait for nearby chunk to be ready in a batch buffer upload.
