### ISSUE TITLE
【bug】电影方块秒数最大上限

### ISSUE THREAD

**Issue by RyanGIggs** [LiXizhi/ParaCraft#215]
电影方块秒数最大上限如果设置4500或者5000这样较大的数值，再次打开电影方块的时候最大上限的秒数会从千位数变成百位数，即4500变成450。

**Comment by ttqf975414890** [comment]
目前可以通过修改电影方块内置命令序列的方法调整电影播放时间，或者调整为永久不停止。

**Comment by LiXizhi** [comment]
之前最大值是3600秒， 目前已经改为任意大了。 
Fixed in next release (已经修复，等下个版本发布. )  Thanks
