### ISSUE TITLE
【bug】记忆方块的动作后，人物皮肤会变回默认的

### ISSUE THREAD

**Issue by RyanGIggs** [LiXizhi/ParaCraft#216]
做了记忆方块的动作后，人物皮肤会变回默认的。

**Comment by LiXizhi** [comment]
![image](https://user-images.githubusercontent.com/94537/31041532-b3f798cc-a5c9-11e7-804a-30512e9ac316.png)

逻辑改为， 如果电影方块中没有对皮肤K帧， 则播放时不会变成默认， 另外主角一定不会换装 

Fixed in next release (已经修复，等下个版本发布. )  Thanks
