### ISSUE TITLE
【bug】方块显示的问题

### ISSUE THREAD

**Issue by RyanGIggs** [LiXizhi/ParaCraft#217]
/block id visible false 使用该指令后 有一定几率触发显示不完全 如图
![qq 20170919155132](https://user-images.githubusercontent.com/16772836/30581513-fa7eae4a-9d52-11e7-96cf-841ca538a63f.jpg)

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
