### ISSUE TITLE
【bug】指令block id visible false

### ISSUE THREAD

**Issue by RyanGIggs** [LiXizhi/ParaCraft#218]
在有大量方块如（id：42）的周围直接输入指令/block 42 visible false 后，显示的阴影不正常。
![qq 20170920101219](https://user-images.githubusercontent.com/16772836/30624045-bb448aba-9ded-11e7-85ad-54fed51227bb.jpg)

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
