### ISSUE TITLE
【bug】setblock按钮出错

### ISSUE THREAD

**Issue by RyanGIggs** [LiXizhi/ParaCraft#219]
用setblock指令增加一个按钮方块，按钮的方向是错的，转动几下显示也出错。如图：
![qq 20170921175353](https://user-images.githubusercontent.com/16772836/30690371-952cefd4-9ef6-11e7-835c-ad02cc87a0c4.jpg)

**Comment by ttqf975414890** [comment]
/setblock [block] [data]
更改 data 可以指定按钮方块的状态。请看清说明再来反馈。这个不属于 bug。

**Comment by LiXizhi** [comment]
```
/setblock ~-1 ~0 ~-2 105:5
```

**Comment by ExerciseBook** [comment]
诡异的反馈。。
setblock可是有6个？参数的。。。
