### ISSUE TITLE
手机版本输入框无法发送消息

### ISSUE THREAD

**Issue by yuki1206** [LiXizhi/ParaCraft#22]
在手机版本的输入框完成输入后，点击发送和取消的按钮无效
![qq 20160614124031](https://cloud.githubusercontent.com/assets/19921244/16031398/34841900-322d-11e6-8bc7-9e13bd6866ba.jpg)

**Comment by LiXizhi** [comment]
无法复现， 不知道是否为最新版。 
看下log.txt
