### ISSUE TITLE
 [安全] Keepwork 账号手机绑定问题

### ISSUE THREAD

**Issue by ExerciseBook** [LiXizhi/ParaCraft#223]
如果我换了手机之后才发现我的KeepWork没有换绑怎么办？

建议可以通过其他的验证来解除手机绑定。

~~其实是有个人来找我说，他的账号被别人盗绑定了 :joy: 我很绝望~~

**Comment by ExerciseBook** [comment]
另：要不加上 非死不可 、 推特 绑定吧，反正都支持了这么多了，不在乎多两个吧  :smirk:

**Comment by LiXizhi** [comment]
@azothli  please move to wikicraft project issues.
