### ISSUE TITLE
【Bug】英文版本下，创建一个新的世界，进入播放模式下，按‘E’键，发现背包信息未更新为英文

### ISSUE THREAD

**Issue by Sandu1213** [LiXizhi/ParaCraft#225]
## The problem
英文版本下，创建一个新的世界，进入播放模式下，按‘E’键，发现背包信息未更新为英文

## Environment

* OS Info: Window10
* App ver: v0.7.340

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.paracraft可以正常打开
* Details:
1.选择英文版本进行后，创建一个新的世界
2.然后切换到播放模式，按下“E”键
3.观察页面展示情况

* Expected Result:
1.页面信息显示正确，都是英文
* Actual Result:
1.页面信息显示为中文，缺少转换
 

## Attachments (eg:logs/video/screenshot)

![image](https://user-images.githubusercontent.com/21214285/32539262-cfb00326-c4a3-11e7-9a72-d6301c3f85e7.png)

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
