### ISSUE TITLE
【Bug】mod和plugin页面的offical Site文字显示不合理

### ISSUE THREAD

**Issue by Sandu1213** [LiXizhi/ParaCraft#226]
## The problem
mod和plugin页面的offical Site文字显示不合理

## Environment

* OS Info: Window10
* App ver: v0.7.340

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.paracraft可以正常打开
* Details:
1.选择英文版本进行后，创建一个新的世界
2.然后切换到编辑模式下，打开window 菜单栏下的Mod和plugin
3.观察页面展示情况

* Expected Result:
1.页面信息显示合理
* Actual Result:
1.页面信息显示不合理，部分文字超限了
 

## Attachments (eg:logs/video/screenshot)
![image](https://user-images.githubusercontent.com/21214285/32540613-30c48606-c4a8-11e7-9f10-0f4811ee60a5.png)

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
