### ISSUE TITLE
【Bug】创建我的世界时，如果名称含有‘.'则无法进行创建，页面卡着不动，应该进行提醒或者限制输入

### ISSUE THREAD

**Issue by Sandu1213** [LiXizhi/ParaCraft#228]
## The problem
创建我的世界时，如果名称含有‘.'则无法进行创建，页面卡着不动，应该进行提醒或者限制输入

## Environment

* OS Info: Window10
* App Info: paracraft ver 0.7.340
* Model:  登录

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，登陆paracraft成功
* Details:
1.选择"create world"，输入名称含“.”时，观察创建结果

* Expected Result:
1.创建我的世界成功
* Actual Result:
1.创建我的世界失败，页面一直卡着不动

## Attachments (eg:logs/video/screenshot)
![createworld](https://user-images.githubusercontent.com/21214285/33113412-34907e66-cf93-11e7-9463-9f3a54652ed3.gif)

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
