### ISSUE TITLE
【Bug】paracraft上传的问题

### ISSUE THREAD

**Issue by Sandu1213** [LiXizhi/ParaCraft#232]
## The problem
paracraft上传的问题

## Environment
* OS Info: Window10
* App Ver: 0.7.341
* Model:  分享世界

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常，打开paracraft成功
* Details:
1.先创造一个世界，上传到keepwork上
2.上传成功后，进行查看，查看完成后将keepwork上的paracraft网站删除
3.此时，不退出paracraft再对之前的世界进行上传或者新建新的世界进行上传，观察上传结果

* Expected Result:
1.上传成功，keepwork上查看正确
* Actual Result:
1.上传失败，keepwork上无任何数据，必须将账号从paracraft退出重新登陆才能正常上传
 ----建议：直接上传成功或者给用户提醒

## Attachments (eg:logs/video/screenshot)

**Comment by LiXizhi** [comment]
@onedou

**Comment by onedou** [comment]
好的，提示提示用户重新登陆吗？

**Comment by onedou** [comment]
提示 paracraft不存在，请重新登陆

**Comment by onedou** [comment]
可以把这个仓也加入board吗
