### ISSUE TITLE
【Bug】创建世界后，添加水元素成功后再添加青金石块，会导致水全部消失，请排查

### ISSUE THREAD

**Issue by Sandu1213** [LiXizhi/ParaCraft#234]
## The problem
创建世界后，添加水元素成功后再添加青金石块，会导致水全部消失，请排查

## Environment

* OS Info: Window10
* App Ver: 0.7.341

## Step To Reproduce Issue [ Good To Have ]

* Pre-conditions:
1.网络正常
* Details:
1.创建一个新的世界，选择"水”，”钻石矿石”，”青金石块“3个元素来搭建
2.先添加水后，再添加青金石块，当添加到第4块时，水元素都消失。

* Expected Result:
1.可以正常添加，元素显示正确
* Actual Result:
1.水元素消失了，撤销操作后又会出现，请排查
 

## Attachments (eg:logs/video/screenshot)
1.附件太大，如果无法重现，请联系我查看附件，谢谢

**Comment by LiXizhi** [comment]
地面上的水是可以堵住的。 任意方块可复习。 

目前就是这样设计的。不是Bug

![image](https://user-images.githubusercontent.com/94537/33516641-2701fb96-d7b1-11e7-8145-7328fd7fac7b.png)
