### ISSUE TITLE
方块显示延迟

### ISSUE THREAD

**Issue by yjstcb** [LiXizhi/ParaCraft#25]
在游戏里面边走边放置或者消除方块，渲染会有延迟。
方块已经敲掉了，但是显示是还在。

**Comment by LiXizhi** [comment]
走路时，计算的线程在运算远处的方块。 目前数目是4个Chunk。 之后才会处理新加入的近处Chunk

**Comment by yjstcb** [comment]
想想办法吧，这个问题最好能解决
