### ISSUE TITLE
【需求】材质方块的扩展

### ISSUE THREAD

**Issue by ghost** [LiXizhi/ParaCraft#279]
Registeritem是个神奇的东西，能够个性化不同性质的方块，但它只能在一个世界里运用，不能同时运用到其他的世界里去，每个世界都要重新注册，很麻烦......请问能不能有个自定义添加材质方块的功能呢？和方块列表里的方块一样能够同时运用到所有的世界，让世界的场景更完美。

**Comment by LiXizhi** [comment]
这个是高级功能， 只需将
blockWorld.lastsave/customblocks.xml 文件复制到其它世界即可

注册的方块， 下个版本可以在E键工具中找到
