### ISSUE TITLE
[建议]希望能够使message box实现多个保留

### ISSUE THREAD

**Issue by yuki1206** [LiXizhi/ParaCraft#28]
目前在不关闭message box的情况下，如果有新的消息占用message box，则会使原有的信息被覆盖
能否使得message box支持多个弹出？

**Comment by LiXizhi** [comment]
希望如何支持呢， 同时显示多个窗口，还是在同一个窗口中显示更多文字。
MessageBox在Win32下默认是只能有一个的。 最好是其他地方查看历史消息。

**Comment by yuki1206** [comment]
仍然只显示一个消息窗口，在点击关闭最上层的消息窗口后，会显示仍未阅读的其他消息窗口，所有消息窗口按时间顺序排列。直到用户将全部消息窗口都点击关闭为止

![image](https://cloud.githubusercontent.com/assets/19921244/16295874/e8a27c8a-395b-11e6-9e90-c4dbeb76b3fa.png)

**Comment by ExerciseBook** [comment]
最好这个窗口可以拖动

**Comment by LiXizhi** [comment]
OK 多层窗口我处理下

**Comment by LiXizhi** [comment]
能否你们指派一个程序员来做。应该不复杂。直接改底层，我担心我们这里其他系统出故障。 然后我会将所有paracraft中用到的MessageBox都改为这种。 这样不影响哈奇那边的逻辑。

**Comment by zhangleio** [comment]
-- public api: append a new general message
-- @param msg: message to be appended
-- @param rootNodeName: if nil, it is "TelephoneMSGRootNode", it can also be "FamilyChatMSGRootNode"
-- e.g. {Name = command.name, icon = icon, nid = nid, tooltip = text, presenceicon = presenceicon, commandName = command.name}
function NotificationArea.AppendMSG(msg, rootNodeName)
可以参考这里的代码，实现弹出的逻辑
