### ISSUE TITLE
版本更新得很快，但总是不知道到底更新了什么，能否描述一下？

### ISSUE THREAD

**Issue by Ashakerty** [LiXizhi/ParaCraft#282]
官方辛苦了，软件也越来越棒了！更新虽然很快，但总是来的莫名其妙......

**Comment by ExerciseBook** [comment]
我记得。。应该会有一个changelog的。不知道现在还有没有。

**Comment by LiXizhi** [comment]
https://github.com/LiXizhi/ParaCraft/wiki/ChangeLog

it is here, we will maintain a user change log soon.
