### ISSUE TITLE
【Bug】进入世界时突然什么都没有，而且无法编辑

### ISSUE THREAD

**Issue by WuDian5D0** [LiXizhi/ParaCraft#287]
1.加载世界的时候会卡顿一下；

2.方块人的皮肤变得很模糊；

3.之后只有场景而没有背包格子；

4.人物可以移动，但不能进行任何除了移动之外的动作，按什么快捷键都无效。

**Comment by Kilimily** [comment]
只能新建一个世界，个人推荐名字取英文的，然后把原来的世界的文件夹中的blockWorld.lastsave文件夹（包括内部的所有文件）和一些其他材质模型文件替换到新建的世界里去。

**Comment by LiXizhi** [comment]
看一下log.txt  应该是出现了runtime error.  出错后， 将安装目录下的log.txt发到这里。

**Comment by BiwnWd** [comment]
[log.txt](https://github.com/LiXizhi/ParaCraft/files/2887703/log.txt)

**Comment by LiXizhi** [comment]
好奇怪的日志， 有很多资源没有下载完毕的  assets remaining. . 

你将出错的世界打包成ZIP，发这里看看?  你用Paracraft， 不用哈奇打开也会出错么？

**Comment by BiwnWd** [comment]
一开始两个都不行，用哈奇打开UI没有发生变化。我一般不在哈奇里面打开，是直接用软件打开的，不过里面的一些文件夹替换到新的世界的文件夹后就恢复正常了。 或许我得重新下载一下软件...
