### ISSUE TITLE
Mac版的，打开之后一直显示正在登陆

### ISSUE THREAD

**Issue by yutingZhou-it** [LiXizhi/ParaCraft#289]
之前登陆之后记住的账号密码，并且选择了自动登陆，然后再过几天之后，打开点击任意位置继续，显示提示，正在登陆，请稍后....

**Comment by sorros** [comment]
我也是显示正在登陆，请稍后。。。。。。。。window版的。

**Comment by sorros** [comment]
更新到最新版本就好了

**Comment by yutingZhou-it** [comment]
已经是最新版的了，卸载重装了很多次了，我把MAC的用户删了创建一个新的用户再下载就好了，不过这样原来用户下面的所有文件就没有了




------------------ 原始邮件 ------------------
发件人: "sorros"<notifications@github.com>;
发送时间: 2019年6月4日(星期二) 上午10:05
收件人: "LiXizhi/ParaCraft"<ParaCraft@noreply.github.com>;
抄送: "周雨婷"<313564624@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [LiXizhi/ParaCraft] Mac版的，打开之后一直显示正在登陆 (#289)




更新到最新版本就好了

**Comment by LiXizhi** [comment]
用最新版。  之前是Token过期导致的，确定修复了。
