### ISSUE TITLE
在水柱中加断层，中间会出现凭空存在的水柱

### ISSUE THREAD

**Issue by yjstcb** [LiXizhi/ParaCraft#29]
在水柱中加断层，中间会出现凭空存在的水柱
![image](https://cloud.githubusercontent.com/assets/13567673/16216186/4b659504-379b-11e6-9dec-51baaef1a3de.png)

**Comment by LiXizhi** [comment]
这个目前就是这样设计的。 Setblock上去的物品，不会影响水的仿真。
正常放上去的物品，才有仿真。 你需要手工删除下面的水。
