### ISSUE TITLE
【疑问】这些红色的都是什么意思？

### ISSUE THREAD

**Issue by ghost** [LiXizhi/ParaCraft#291]
红色的白色方块可以染色，我猜想后面的都可以染色才对，网站里也没有详细的解释。
![QQ截图20190717094120](https://user-images.githubusercontent.com/43124921/61341219-11d19300-a878-11e9-8f47-d1e562e64d25.png)

**Comment by LiXizhi** [comment]
用代码都可以染色。 但是给用户只开放了几个。
