### ISSUE TITLE
魔法哈奇“实名认证失败，请重试”

### ISSUE THREAD

**Issue by Caciapaglia** [LiXizhi/ParaCraft#298]
[最近放假得空想找寻一下童年回忆，然后发现实名认证一直失败，如图，请问是什么原因？谢谢！
![IUA)9FA5KBBBVKX{8H0Z%OP](https://user-images.githubusercontent.com/109129870/178416547-3040e293-8bf1-44bc-bf6b-c2a22133e6f0.png)

**Comment by Caciapaglia** [comment]
姓名和身份证号确认都是对的，还借用朋友的实名信息尝试了一下，均显示实名失败。 @LiXizhi

**Comment by fengyinz** [comment]
这只是卡了 换个浏览器 或者刷新一下

**Comment by Caciapaglia** [comment]
> 

qq浏览器和360浏览器都试过了，还用手机上的浏览器试了一下，还是失败…

**Comment by Caciapaglia** [comment]
> 这只是卡了 换个浏览器 或者刷新一下

qq浏览器和360浏览器都试过了，还在手机上的浏览器试了下，还是失败…

**Comment by fengyinz** [comment]
再多换几个浏览器试试 最好是改默认的 或者让别人帮你实名试试 我好像昨天都还可以的

**Comment by fengyinz** [comment]
好吧我也失败了 看来真出问题了

**Comment by Caciapaglia** [comment]
> 再多换几个浏览器试试 最好是改默认的 或者让别人帮你实名试试 我好像昨天都还可以的 

好的谢谢你！我去试试

**Comment by fengyinz** [comment]
我也失败了

**Comment by fengyinz** [comment]
看来真出问题了

**Comment by Caciapaglia** [comment]
> 好吧我也失败了 看来真出问题了

啊啊啊好吧，谢谢你！

**Comment by fengyinz** [comment]
现在可以实名了
