### ISSUE TITLE
F3info里的坐标信息消失

### ISSUE THREAD

**Issue by yjstcb** [LiXizhi/ParaCraft#3]
版本：0.7.243
按F3打开信息栏，里面mouse 和 relative to 两排坐标信息不见。
并且按相应快捷键，复制的是空字符串，如下图
![image](https://cloud.githubusercontent.com/assets/13567673/14338354/061c5dfc-fca9-11e5-9243-4795ee30054f.png)
![image](https://cloud.githubusercontent.com/assets/13567673/14338375/41d72dd6-fca9-11e5-8271-d93473a73394.png)

**Comment by LiXizhi** [comment]
Fixed.
