### ISSUE TITLE
[BUG]图片框无法使用外网的绝对路径

### ISSUE THREAD

**Issue by yuki1206** [LiXizhi/ParaCraft#30]
![image](https://cloud.githubusercontent.com/assets/19921244/16259280/6aea8c96-3894-11e6-9e52-d1cef0fc5a4d.png)

**Comment by LiXizhi** [comment]
Fixed in next release

![uploadimg](https://cloud.githubusercontent.com/assets/94537/16260495/47be987e-389a-11e6-9437-9d1912966129.png)
