### ISSUE TITLE
[建议]希望在联机环境下实现告示牌、物品显示框、图片框的同步

### ISSUE THREAD

**Issue by yuki1206** [LiXizhi/ParaCraft#31]
能够实现效果的同步，但加入房间的玩家右键后仍然不能打开编辑

**Comment by LiXizhi** [comment]
- Fixed in next release
- blockSign, blockImage, blockItemFrame can now be synced in remote world. Both client and server can edit these entities

![imagesync](https://cloud.githubusercontent.com/assets/94537/16291469/fa711254-3939-11e6-9ce1-4a0264c00ff0.png)
