### ISSUE TITLE
滚动条控件

### ISSUE THREAD

**Issue by yjstcb** [LiXizhi/ParaCraft#33]
滚动条，鼠标点击下图位置滚动条标识拖动后，在滚动条区域外放开鼠标，实际未解除选中状态，鼠标再移动到滚动条其他位置，标识会跟着移动
![image](https://cloud.githubusercontent.com/assets/13567673/16300018/2110fbaa-3970-11e6-8f23-c6d2ba8cca54.png)

**Comment by LovelyCatHyt** [comment]
每一个滚动条都是这样，包括命令行书、命令方块等

**Comment by LiXizhi** [comment]
Fixed in next release
