### ISSUE TITLE
水面层级问题

### ISSUE THREAD

**Issue by yjstcb** [LiXizhi/ParaCraft#36]
从水面的视角看，鼠标over到水中的entity上，模型会消失。如下图
![image](https://cloud.githubusercontent.com/assets/13567673/16367847/2ce291f4-3c5a-11e6-8082-c2ff00c3c2e7.png)

**Comment by LiXizhi** [comment]
Fixed in next release
![underwater](https://cloud.githubusercontent.com/assets/94537/16576490/242bdf7a-42c2-11e6-8178-8b26d0cca4f1.png)
