### ISSUE TITLE
shift+右键操作后ctrl+z 撤销不干净

### ISSUE THREAD

**Issue by yjstcb** [LiXizhi/ParaCraft#38]
![image](https://cloud.githubusercontent.com/assets/13567673/16510543/9f3bb7d6-3f79-11e6-9b00-56b47f143613.png)
将楼梯或者藤蔓放在树上，然后shift+右键操作后撤销，有很大概率撤销不干净

**Comment by LiXizhi** [comment]
无法复现，请提供更详细的复现步骤，谢谢~

**Comment by LiXizhi** [comment]
问题找到了
Fixed in next release

**Comment by LiXizhi** [comment]
- Fixed a low level rendering bug when neighboring blocks are set dirty in the same frame, causing one or two blocks not updated.
