### ISSUE TITLE
告示牌文字和相册图片飞走了

### ISSUE THREAD

**Issue by LovelyCatHyt** [LiXizhi/ParaCraft#39]
如图。。貌似文字会跟着人物的动作运动
而且好像是只有我这一台电脑会这样。
![image](https://cloud.githubusercontent.com/assets/20336911/16650732/59be8fd2-4472-11e6-9990-3d63f337d994.png)

**Comment by LovelyCatHyt** [comment]
相册也是类似的情况，就不截图了

**Comment by LovelyCatHyt** [comment]
补充：电影模式下，操控人物时，那个被操控的人物会消失（左下角显示“动作”）
而其他视角可以看到该人物
![image](https://cloud.githubusercontent.com/assets/20336911/16705402/836454bc-45bb-11e6-969b-6712fbde56dd.png)
![image](https://cloud.githubusercontent.com/assets/20336911/16705406/9b4309d4-45bb-11e6-830c-6f9a7511de6f.png)

坐标轴、电影模式下的所有类似坐标轴的物体都会飞；
![image](https://cloud.githubusercontent.com/assets/20336911/16705413/da50a032-45bb-11e6-943f-55daa0923247.png)

电脑系统是Winxp的

**Comment by LiXizhi** [comment]
> 貌似文字会跟着人物的动作运动

这个问题很奇怪。 建议升级下系统试试， 是否是显卡问题

感觉都是同一个问题引起的。 是否有log.txt可以发这里看下。

**Comment by LovelyCatHyt** [comment]
[log.txt](https://github.com/LiXizhi/ParaCraft/files/363038/log.txt)

**Comment by LiXizhi** [comment]
log中显示
HAL (pure hw vp): ATI RADEON XPRESS 200 Series |
VS:2 PS:2

显卡太弱。 需要的Shader无法加载。
