### ISSUE TITLE
联机：加入主机后跳跃高度不正常

### ISSUE THREAD

**Issue by yjstcb** [LiXizhi/ParaCraft#4]
版本：0.7.243
加入到一个主机之后，跳跃高度会非常低。但是主机的跳跃高度是正常的。
![image](https://cloud.githubusercontent.com/assets/13567673/14339142/e075d2ee-fcae-11e5-9c3d-fbfef8a9b3ed.png)

**Comment by LiXizhi** [comment]
fixed
