### ISSUE TITLE
bmax与彩色方块一起保存后自动关闭

### ISSUE THREAD

**Issue by LovelyCatHyt** [LiXizhi/ParaCraft#40]
第一步
![image](https://cloud.githubusercontent.com/assets/20336911/16705332/fe3591b8-45b8-11e6-9014-dfaff048dd8b.png)
第二步
![image](https://cloud.githubusercontent.com/assets/20336911/16705334/07593c22-45b9-11e6-9e10-e7404af9bbe7.png)
第三步：把刚刚的bmax模型放到那个缺口上，重新将整个保存为bmax
![image](https://cloud.githubusercontent.com/assets/20336911/16705335/1b235198-45b9-11e6-85ef-e0f7254cb3e1.png)
（名字还是test）
然后一按确定，窗口消失。

**Comment by LiXizhi** [comment]
bmax模型是引用的关系。不能重名。
我修复下Crash的问题

**Comment by LiXizhi** [comment]
- fixed a crash if bmax model reference other models recursively.
Fixed in next release
