### ISSUE TITLE
bmax使用shift+右键快捷操作会产生透明物体

### ISSUE THREAD

**Issue by LovelyCatHyt** [LiXizhi/ParaCraft#42]
![image](https://cloud.githubusercontent.com/assets/20336911/16705357/f3a049fe-45b9-11e6-89a0-1b7073f9a257.png)
原本是只有一个模型
然后shift+右键点它
![image](https://cloud.githubusercontent.com/assets/20336911/16705361/07546b4c-45ba-11e6-876c-63c7d72443c7.png)
出现三个透明的物体
我猜是没有进行导入？

**Comment by LovelyCatHyt** [comment]
并且alt+左键并不能获取这个方块

**Comment by LiXizhi** [comment]
这个问题已经解决了。
Fixed in next release
