### ISSUE TITLE
有关动画信息逻辑设定的改进设想

### ISSUE THREAD

**Issue by yuki1206** [LiXizhi/ParaCraft#43]
现阶段我们的角色骨骼保持不变的情况下能不能统一调用一套动画信息。每次导出模型只需要导出蒙皮好的。共用一套动画。目前每次导出角色包含动画的容量是3M，不包含动画的是900多KB。
当动画角色进一步增加时，不仅会产生大量重复无用的数据，也会出现部分角色动作产生问题

**Comment by yuki1206** [comment]
dexter(王帅) 18:35:01
未来随着我们角色和npc的增加。如果还是按照目前的导出方式，会使游戏容量增大

**Comment by LiXizhi** [comment]
可以的。 但是骨骼不能改变。

**Comment by LiXizhi** [comment]
added new command
/anim filename.fbx
