### ISSUE TITLE
[建议]希望联机模式实现entity的命令同步

### ISSUE THREAD

**Issue by yuki1206** [LiXizhi/ParaCraft#45]
目前遇到的命令主要是【move】，当触发这条命令时，会将房主移动到命令指定的地点。
希望使【/move @】命令能够支持到加入房间的玩家，比如根据进入房间用户的前后顺序给予的编号，或是米米号，用户名等等
同样的还有【/facing】和【/lookat】、【/anim】、【/walk】
这几个可能都会在联机中用到

**Comment by ExerciseBook** [comment]
其实。。这个命令
本来是 @后面跟着的是 NPC的名字 _(:з」∠)_ 【可以在xml里面找到的name标签】
联机状态下我就不知道这个东西到底是啥了。。。

**Comment by LiXizhi** [comment]
`/move @p  home`    可用于触发对象， 或对象名字。 
例如 `/move @__MP__355337906  home`  

其他命令请单独写issue吧 

    - /teleport command are made local
     - /move command is now handled by entity function so that server can set client player's position regardless of client reset.
     - Server can now handle commands entered on the client's console with proper fromEntity set. 
     - server side remote player teleport logic is done. A new packet PacketEntityMove is added.
