### ISSUE TITLE
[bug]楼梯类型的方块使用镜像后方向不变

### ISSUE THREAD

**Issue by LovelyCatHyt** [LiXizhi/ParaCraft#47]
如题，有的时候必须要镜像，但是楼梯却因为这个bug需要一个个摆。图就不需要了吧

**Comment by LiXizhi** [comment]
好的 我修复下 之前记得改过来自我的华为手机-------- 原始邮件 --------主题：[LiXizhi/ParaCraft] [bug]楼梯类型的方块使用镜像后方向不变 (#47)发件人：LovelyCatHyt 收件人：LiXizhi/ParaCraft 抄送：如题，有的时候必须要镜像，但是楼梯却因为这个bug需要一个个摆。图就不需要了吧

**Comment by ExerciseBook** [comment]
论邮件回复的尴尬。。。

**Comment by LiXizhi** [comment]
- block stair implemented mirror operation
Fixed in next release
