### ISSUE TITLE
[bug]相册显示图片错误

### ISSUE THREAD

**Issue by Soul-Kim** [LiXizhi/ParaCraft#48]
![qq 20160719163127](https://cloud.githubusercontent.com/assets/17987561/16943545/d4c402ce-4dce-11e6-85d2-f5c25bdd3b1f.jpg)
![1](https://cloud.githubusercontent.com/assets/17987561/16943546/d4dee648-4dce-11e6-980e-8a402bebd695.jpg)
 连续的两块接不上

**Comment by LiXizhi** [comment]
Fixed in next release

![image](https://cloud.githubusercontent.com/assets/94537/17010836/42a1d7f0-4f3a-11e6-991b-d91fc9e0df95.png)
