### ISSUE TITLE
静态水和动态水存在色差

### ISSUE THREAD

**Issue by yuki1206** [LiXizhi/ParaCraft#49]
如题，在半空中查看时，可见两种水之间有色差。使用replace好像无法在两种水之间进行转换
总之这块地方很难修复到完美如初的状态
![image](https://cloud.githubusercontent.com/assets/19921244/16973678/22db5d7e-4e68-11e6-928f-ad1427b5bd37.png)

**Comment by LiXizhi** [comment]
渲染没有区别。 保存后重启，应该就好了。 只是Replace造成的临时的光照计算的问题。
