### ISSUE TITLE
相册靠近游戏窗口顶端后出错

### ISSUE THREAD

**Issue by jetkidlay** [LiXizhi/ParaCraft#56]
![image](https://cloud.githubusercontent.com/assets/20693592/17199615/c0256432-54b0-11e6-9799-5f9f4346737f.png)
首先这个是正常的相片
![image](https://cloud.githubusercontent.com/assets/20693592/17199598/a1776a76-54b0-11e6-95f5-2367baad9e93.png)
镜头往下拖动，等相册接近上方游戏窗口的时候，相片就出现问题了

**Comment by LiXizhi** [comment]
世界请发我下， 我这里无法复现

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
Fixed in C++
