### ISSUE TITLE
半砖如图放置，玩家重新进入房间后方块位置错误

### ISSUE THREAD

**Issue by jetkidlay** [LiXizhi/ParaCraft#57]
主机放置
![image](https://cloud.githubusercontent.com/assets/20693592/17205609/3c7b0c80-54de-11e6-986d-bfd57de0b09b.png)
玩家视角
![image](https://cloud.githubusercontent.com/assets/20693592/17205878/7e82d008-54df-11e6-9075-c24971fc32d7.png)
玩家再次进入时视角
![image](https://cloud.githubusercontent.com/assets/20693592/17205857/6b3f8ef0-54df-11e6-8db4-27e369d3c258.png)

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
