### ISSUE TITLE
[bug]穿墙术

### ISSUE THREAD

**Issue by LovelyCatHyt** [LiXizhi/ParaCraft#58]
很久远的bug了
这是一个普通的斜面↓

然后按f开飞行模式之后，往上飞，理论上来讲会被挡住，但是。。。我居然飞出去了？
（貌似图片上传不了？）

**Comment by LovelyCatHyt** [comment]
![default](https://cloud.githubusercontent.com/assets/20336911/17238221/77e1099c-558c-11e6-8556-5a0ebb7504e2.png)

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )

**Comment by ExerciseBook** [comment]
开发者大大隔空听到了hyt和我私聊时候的吐槽于是这次用了中文
