### ISSUE TITLE
[BUG]疑似大批量相册无法成功加载

### ISSUE THREAD

**Issue by ExerciseBook** [LiXizhi/ParaCraft#59]
![第一次打开](https://cloud.githubusercontent.com/assets/6327311/17275884/594f523a-574a-11e6-882f-625ae5f5d001.jpg)
![第二次打开j](https://cloud.githubusercontent.com/assets/6327311/17275885/59ecb516-574a-11e6-9864-1291855669af.jpg)

存档发不上来，已私发到你的邮箱。

**Comment by LiXizhi** [comment]
无法复现，请提供更详细的复现步骤，谢谢~
