### ISSUE TITLE
联机：移动方块bug

### ISSUE THREAD

**Issue by yjstcb** [LiXizhi/ParaCraft#6]
版本：0.7.244
联机时，非主机玩家 选中大片方块快速移动时，会在移动路径上造成方块“残影”，详见下图
![image](https://cloud.githubusercontent.com/assets/13567673/14455917/b9269c9e-00d4-11e6-978f-0b5521dae14f.png)

**Comment by LiXizhi** [comment]
should be fixed. in next release
