### ISSUE TITLE
非主机用户上矿车无法加载地图

### ISSUE THREAD

**Issue by jetkidlay** [LiXizhi/ParaCraft#61]
![image](https://cloud.githubusercontent.com/assets/20693592/17351778/09bb4442-5964-11e6-834c-85c6258aeca2.png)
非主机用户在矿车行进一段距离后就不会再加载地图了

**Comment by LiXizhi** [comment]
我可以复现了，谢谢，会尽快修复

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
