### ISSUE TITLE
联机模式下矿车乘坐问题

### ISSUE THREAD

**Issue by jetkidlay** [LiXizhi/ParaCraft#64]
![image](https://cloud.githubusercontent.com/assets/20693592/17426959/895cbec2-5b0f-11e6-99d9-7eab34f07fde.png)
多人联机模式下，玩家你在逗我正在搭乘矿车，此时玩家阿斯达点击了你在逗我所乘坐的矿车，在阿斯达的画面中，看到你在逗我被破下了矿车，但在你在逗我的画面中，他依然乘坐着矿车
![image](https://cloud.githubusercontent.com/assets/20693592/17426950/743041c2-5b0f-11e6-899e-ebfcc572dd4a.png)

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
