### ISSUE TITLE
[bug]命令行书中的命令无法正确显示缩进

### ISSUE THREAD

**Issue by LovelyCatHyt** [LiXizhi/ParaCraft#65]
在命令行书中，我输入了如下命令：
/if 【具体内容省略】
[空格]/if ......
[空格][空格]/setblock ......
[空格]/fi
/fi
然而保存之后，下一次进入世界打开命令行书看到的却是：
/if ......
[空格]/if ......
[空格]/setblock......
[空格]/fi
/fi
目测是把多个空格变为一个空格了

**Comment by LiXizhi** [comment]
- fixed ItemCommandLine can not save two consecutive empty space characters

Fixed in next release (已经修复，等下个版本发布. )  Thanks
