### ISSUE TITLE
人物在水中时名字会消失

### ISSUE THREAD

**Issue by jetkidlay** [LiXizhi/ParaCraft#66]
![image](https://cloud.githubusercontent.com/assets/20693592/17508411/64769fd4-5e47-11e6-9e51-92ad1abea1ca.png)
![image](https://cloud.githubusercontent.com/assets/20693592/17508415/6af57cfe-5e47-11e6-9f7c-21d8024643d0.png)

**Comment by ExerciseBook** [comment]
图层的问题2333【吧

**Comment by ExerciseBook** [comment]
![图1](http://ww3.sinaimg.cn/large/8ddab624gw1f6ptbgdbhqj20zq0kswtp.jpg)

水面上
![图2](http://ww2.sinaimg.cn/large/8ddab624gw1f6ptbiw20tj20zq0ks4cb.jpg)
水面下
![图3](http://ww2.sinaimg.cn/large/8ddab624gw1f6ptbki7zwj20zq0ks46p.jpg)

突然间上传不了 图片到github了，将就用着新浪吧。

可以确定是图层错了

**Comment by LiXizhi** [comment]
#79 repeated
