### ISSUE TITLE
【彩色方块同步相关错误】

### ISSUE THREAD

**Issue by ExerciseBook** [LiXizhi/ParaCraft#67]
我看到的内容是这样的
![b](https://cloud.githubusercontent.com/assets/6327311/17508914/f46fadea-5e49-11e6-96cc-0e982a650217.png)

别人看到的内容是这样的
![2](https://cloud.githubusercontent.com/assets/6327311/17508927/ff4b0796-5e49-11e6-9fa8-f2dfe238c8ef.png)
甚至是这样的
![3](https://cloud.githubusercontent.com/assets/6327311/17508928/002a4636-5e4a-11e6-94a2-95f1fd2ced2a.png)

这里是坐标相关
![1](https://cloud.githubusercontent.com/assets/6327311/17508953/1edbe4d6-5e4a-11e6-907e-0f64ec8544df.jpg)

**Comment by LiXizhi** [comment]
无法复现，请提供更详细的Paracraft中的复现步骤
