### ISSUE TITLE
The Secret of Disappearing ChangeLog

### ISSUE THREAD

**Issue by ExerciseBook** [LiXizhi/ParaCraft#70]
https://www.evernote.com/shard/s177/sh/afe666c9-e398-4367-8756-8a69e79b8db0/c0dd35bb5bf25425bd09e06eb1ffe918
![表情](https://cloud.githubusercontent.com/assets/6327311/17650087/d775fbbe-6276-11e6-8527-17dce5cf5264.jpg)万众期待的Changelog怎么不见了。快搬回来！新功能认识全指望在它身上了！

**Comment by LiXizhi** [comment]
http://www.evernote.com/l/ALGymMtcwlJDT5c6frUlCQPzTAbHn8LqLwE/
