### ISSUE TITLE
[Suggestion] 方块表达式扩展

### ISSUE THREAD

**Issue by ExerciseBook** [LiXizhi/ParaCraft#71]
/fill 62 已经不能满足我们了
我们需要
/fill 50%62,50%92
/fill 50%62,50%92
/fill 33%62,33%92,34%0
这种东西来显示出这个游戏的厉害；
【应该是正则大法好。

**Comment by LiXizhi** [comment]
deprecated. use terrain brush

**Comment by ExerciseBook** [comment]
在做一些古建筑的道路上也许有用。
因为可以夹杂一些不同的石头表示 "这个建筑很古老"
比如说碎石头
