### ISSUE TITLE
关于光照渲染错误的进一步说明

### ISSUE THREAD

**Issue by ExerciseBook** [LiXizhi/ParaCraft#72]
上次在https://github.com/LiXizhi/ParaCraftSDK/issues/3
提交的问题，我感觉我们提交的，和你修复的不是同一个问题。。。

一楼发存档。【自行把下面这张图片后缀改成zip。我懒得上传百度云了。。。
![存档](https://cloud.githubusercontent.com/assets/6327311/17655676/aca4bea8-62e3-11e6-97b2-83961bb5af2a.jpg)

**Comment by ExerciseBook** [comment]
小寂提供的截图。
![xp](https://cloud.githubusercontent.com/assets/6327311/17655756/a57c5040-62e4-11e6-998e-b0ca56e4a469.jpg)
![xp1](https://cloud.githubusercontent.com/assets/6327311/17655755/a57b60ae-62e4-11e6-87ba-aae5544db0c1.jpg)
![xp2](https://cloud.githubusercontent.com/assets/6327311/17655757/a5b42038-62e4-11e6-91d3-fa4a91ab90cc.jpg)

从我电脑的截图
![Win7](http://ww4.sinaimg.cn/large/8ddab624gw1f6ubskzl3mj211k0mewnf.jpg)
【上传个文件到github都这么困难。。。

日光日白这么黑，我是不是瞎了。。。。

**Comment by LiXizhi** [comment]
by design, not a bug. sun light can only go as far as 16 blocks.
