### ISSUE TITLE
【不鬼畜】【很严重】说好的Chunks自动卸载呢？

### ISSUE THREAD

**Issue by ExerciseBook** [LiXizhi/ParaCraft#74]
我今天用鼠标中键去试一下能不能炸房，然后就炸掉了。。。。。
【用中键瞬移，不断往远处走，使房主不断载入chunks直到炸掉

**Comment by LovelyCatHyt** [comment]
好。。。简洁的描述
这个。。感觉好像不很严重
虽然后果很严重
但是 好像没有人会这么做吧？

**Comment by ExerciseBook** [comment]
其实潜台词是，如果你的建筑很大，需要载入比较多的区域的话，和这个是同一样的结果

**Comment by LovelyCatHyt** [comment]
目前 貌似 没有这么大的建筑
是我就拖延 #滑稽

**Comment by LiXizhi** [comment]
无法复现
