### ISSUE TITLE
setblock方块不同步

### ISSUE THREAD

**Issue by yjstcb** [LiXizhi/ParaCraft#75]
![image](https://cloud.githubusercontent.com/assets/13567673/17693700/d359fa8c-63d2-11e6-803c-50b551ede632.png)
联机过程中，命令方块里面用/setblock命令消除一堵厚墙（就是ID设成0），然后由其他玩家触发命令方块，则整堵墙消失不干净，如上图

**Comment by LiXizhi** [comment]
无法复现，请提供更详细的复现步骤，谢谢~
