### ISSUE TITLE
水和玻璃片、彩色方块会遮挡角色名

### ISSUE THREAD

**Issue by jetkidlay** [LiXizhi/ParaCraft#79]
![image](https://cloud.githubusercontent.com/assets/20693592/17842271/a6648a8a-6853-11e6-8030-b3ac664b5fdc.png)
![image](https://cloud.githubusercontent.com/assets/20693592/17842287/cbc6ea66-6853-11e6-8536-610ddfa2bf21.png)

**Comment by LiXizhi** [comment]
目前暂时无法实现这个功能。 否则会引起另外一个显示问题。
