### ISSUE TITLE
【shader】开shader的同时开真实光影会亮瞎眼

### ISSUE THREAD

**Issue by yjstcb** [LiXizhi/ParaCraft#8]
version：0.7.250
开了shader+真实光影以后，发光的方块会异常亮。闪瞎狗眼。
开启前：
![image](https://cloud.githubusercontent.com/assets/13567673/15107052/feabb48a-15ff-11e6-8c31-805d761d0633.png)
开启后：
![image](https://cloud.githubusercontent.com/assets/13567673/15107057/07f42df6-1600-11e6-82dd-1344ce0da39a.png)

**Comment by LiXizhi** [comment]
中间那条在影子中的为何那么的亮。看不清具体结构。 

近处那个是正常的。 因为是白色。

**Comment by yjstcb** [comment]
亮的那些白色方块下面有发光方块，只要是开了SHADER和真实光影，发光方块就会特别亮，还会影响到四周的方块
