### ISSUE TITLE
天气与时间不同步

### ISSUE THREAD

**Issue by jetkidlay** [LiXizhi/ParaCraft#80]
![image](https://cloud.githubusercontent.com/assets/20693592/17842610/374ce9c2-6857-11e6-81a8-a104ea3f0571.png)

**Comment by LiXizhi** [comment]
https://github.com/LiXizhi/ParaCraft/wiki/cmd_runat

新增runat 命令，同步：

```
/runat @all  /time 0.5
```

Fixed in next release (已经修复，等下个版本发布. )  Thanks
