### ISSUE TITLE
相册多人同步问题

### ISSUE THREAD

**Issue by ExerciseBook** [LiXizhi/ParaCraft#83]
我把url放在了左上角
这是房主的视角
![qq 20160823213840](https://cloud.githubusercontent.com/assets/6327311/17893925/12c5465c-697a-11e6-9c50-8ffb7b268018.png)

这是不明真相的围观群众的视角
![5dz g 6wgl0 y jb7s_zs](https://cloud.githubusercontent.com/assets/6327311/17893934/179641d6-697a-11e6-82eb-44daa3873b83.png)

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )
