### ISSUE TITLE
家具功能

### ISSUE THREAD

**Issue by yjstcb** [LiXizhi/ParaCraft#84]
新增家具mount point  @LiXizhi

**Comment by LiXizhi** [comment]
[Model block](https://github.com/lixizhi/paracraft/wiki/item_blockmodel)  bmax支持了下。 
任意模型物理还要等下

**Comment by LiXizhi** [comment]
now fully supported, see here via [PhysicsBlock](https://github.com/LiXizhi/ParaCraft/wiki/item_PhysicsModel)
