### ISSUE TITLE
【建议】【需求】唱片机支持url

### ISSUE THREAD

**Issue by ExerciseBook** [LiXizhi/ParaCraft#85]

**Comment by ExerciseBook** [comment]
e.g.

/music @目标玩家 http://tts.baidu.com/text2audio?lan=en&pid=101&ie=UTF-8&idx=1&tex=example&per=0&ctp=1&cuid=1&pdt=1
/music @目标玩家 http://tts.baidu.com/text2audio?lan=zh&pid=101&ie=UTF-8&idx=1&tex=%E4%B8%BE%E4%B8%AA%E4%BE%8B%E5%AD%90&per=0&ctp=1&cuid=1&pdt=1
/music @目标玩家 http://tts.baidu.com/text2audio?lan=cte&pid=101&ie=UTF-8&idx=1&tex=%E4%B8%BE%E4%B8%AA%E4%BE%8B%E5%AD%90&per=0&ctp=1&cuid=1&pdt=1

**Comment by ExerciseBook** [comment]
打算用在游戏里面的广播。

**Comment by LiXizhi** [comment]
- http://tts.baidu.com/text2audio?lan=zh&ie=UTF-8&spd=5&text=任意文字
  - spd is voice speed 
- /voice command added 

Fixed in next release (已经修复，等下个版本发布. )

**Comment by ExerciseBook** [comment]
害怕。 是单纯的百度语音助手还是http的mp3链接？
我觉得这个还可以用来在多人模式下播放音乐。
