### ISSUE TITLE
摄像机穿墙

### ISSUE THREAD

**Issue by ExerciseBook** [LiXizhi/ParaCraft#87]
![paperstar-2016-08-28-13-57-07-746](https://cloud.githubusercontent.com/assets/6327311/18031939/c03beb14-6d27-11e6-814b-89425fc6da47.gif)
没有封顶

**Comment by LovelyCatHyt** [comment]
这个神奇的bug简直不能忍
到了这个时候只能选择F5了
希望能尽快修复哈

**Comment by LiXizhi** [comment]
- 在有太阳光进入的地方会这样。 防止在树林里走时，摄影机乱动。 下个版本， 我做一个属性

**Comment by LiXizhi** [comment]
- added new attribute IgnoreEyeBlockCollisionInSunlight to camera attribute. or 
- via command line `/property set -camera IgnoreEyeBlockCollisionInSunlight false`

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
