### ISSUE TITLE
游戏后台运行的时候粒子效果之类的特效不会活动，长期积累容易卡成狗

### ISSUE THREAD

**Issue by ExerciseBook** [LiXizhi/ParaCraft#88]
![default](https://cloud.githubusercontent.com/assets/6327311/18034401/ae4ea67a-6d6e-11e6-81d2-d28515f1c925.png)
↑如图

比如说方块被破坏的时候的粒子效果之类的。在多人模式下常见。
【又比如说通过GameLogic.GetWorld():CreateBlockPieces召唤的那些

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )
