### ISSUE TITLE
半透明贴图GG

### ISSUE THREAD

**Issue by ExerciseBook** [LiXizhi/ParaCraft#89]
![qq 20160830155402](https://cloud.githubusercontent.com/assets/6327311/18080908/fef91112-6ec9-11e6-8955-1712e1bf0b79.png)
手中的半透明方块放出来就全透明了

**Comment by LiXizhi** [comment]
请提供更详细的复现步骤

**Comment by ExerciseBook** [comment]
/registeritem XXXXX

{{
<block id="2513" base_block_id="95" transparent="true" texture="texture/glass/glass_red.png" alphaTestTexture="true"/>
<block id="2505" base_block_id="95" transparent="true" texture="texture/glass/glass_gray.png" alphaTestTexture="true"/>
<block id="2501" base_block_id="95" transparent="true" texture="texture/glass/glass_black.png" alphaTestTexture="true"/>
<block id="2514" base_block_id="95" transparent="true" texture="texture/glass/glass_silver.png" alphaTestTexture="true"/>
<block id="2506" base_block_id="95" transparent="true" texture="texture/glass/glass_green.png" alphaTestTexture="true"/>
<block id="2502" base_block_id="95" transparent="true" texture="texture/glass/glass_blue.png" alphaTestTexture="true"/>
<block id="2515" base_block_id="95" transparent="true" texture="texture/glass/glass_white.png" alphaTestTexture="true"/>
<block id="2511" base_block_id="95" transparent="true" texture="texture/glass/glass_pink.png" alphaTestTexture="true"/>
<block id="2503" base_block_id="95" transparent="true" texture="texture/glass/glass_brown.png" alphaTestTexture="true"/>
<block id="2507" base_block_id="95" transparent="true" texture="texture/glass/glass_light_blue.png" alphaTestTexture="true"/>
<block id="2504" base_block_id="95" transparent="true" texture="texture/glass/glass_cyan.png" alphaTestTexture="true"/>
<block id="2509" base_block_id="95" transparent="true" texture="texture/glass/glass_magenta.png" alphaTestTexture="true"/>
<block id="2510" base_block_id="95" transparent="true" texture="texture/glass/glass_orange.png" alphaTestTexture="true"/>
<block id="2512" base_block_id="95" transparent="true" texture="texture/glass/glass_purple.png" alphaTestTexture="true"/>
<block id="2516" base_block_id="95" transparent="true" texture="texture/glass/glass_yellow.png" alphaTestTexture="true"/>
<block id="2508" base_block_id="95" transparent="true" texture="texture/glass/glass_lime.png" alphaTestTexture="true"/>
<block id="2500" base_block_id="95" transparent="true" texture="texture/glass/glass.png" alphaTestTexture="true"/>
}}

**Comment by LiXizhi** [comment]
'/register #%&*??/;:_-)'  具体内容发过来

**Comment by ExerciseBook** [comment]
/registeritem -alphaTestTexture 2508 texture/glass/glass_lime.png

![glass_lime](https://cloud.githubusercontent.com/assets/6327311/18113099/af905c84-6f5f-11e6-9502-a9e6d33e538d.png)

**Comment by LiXizhi** [comment]
see: https://github.com/LiXizhi/ParaCraft/wiki/cmd_registeritem
