### ISSUE TITLE
【建议】[数据同步折中方案]关于如何折中处理部分命令/属性设置无法同步

### ISSUE THREAD

**Issue by ExerciseBook** [LiXizhi/ParaCraft#94]
我们可以加一个功能，就是向制定玩家发送命令。让这个玩家在本地执行这个命令，这样可以避免部分功能【比如说时间，碰撞箱之类的】无法同步的尴尬了。
【不过滥用感觉也很诡异 /open

**Comment by LiXizhi** [comment]
https://github.com/LiXizhi/ParaCraft/wiki/cmd_runat

#80 

Fixed in next release (已经修复，等下个版本发布. )  Thanks
