### ISSUE TITLE
alt+shift+右键bug

### ISSUE THREAD

**Issue by yjstcb** [LiXizhi/ParaCraft#98]
复现方法：
1.随便放4个以上同样的铁轨（什么铁轨都行）
![image](https://cloud.githubusercontent.com/assets/13567673/18613404/a0bffec0-7dac-11e6-88ed-331745716732.png)
2.手里拿着铁轨（与上面相同）
3.alt+shift+右键点击铁轨就会非常卡，且会卡一段时间

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
